# Use official Python 3.11 image as base
FROM python:3.11-alpine

# Set working directory in the container
WORKDIR /app

# Copy requirements.txt to the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY app.py .

EXPOSE 8000

# Set Flask environment variables
ENV FLASK_RUN_PORT=8000 FLASK_RUN_HOST=0.0.0.0

# Command to run the application
CMD ["flask", "run", "--debug"]
