version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
  db:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.mysql
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_TCP_PORT: 8889
      MYSQL_DATABASE: classicmodels
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    ports:
      - "8889:8889"
    volumes:
      - ./mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/mysqlsampledatabase.sql
